#!/usr/bin/env bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

g++ -std=c++11 \
    -I/usr/include/jsoncpp -I/usr/local/include/jsoncpp \
    generate-ellipsoid.cpp \
    -lentwine -lpdalcpp \
    -o generate-ellipsoid && \
    ./generate-ellipsoid

