name: entwine
channels:
  - conda-forge
dependencies:
  - compilers
  - cmake
  - ninja
  - pip
  - pip:
    - breathe
    - pybtex
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
    - sphinxcontrib-spelling
