name: entwine
channels:
  - conda-forge
dependencies:
  - compilers
  - cmake
  - ninja
  - pip
  - pip:
    - breathe
    - pybtex
    - sphinx-rtd-theme
    - sphinx > 6
    - sphinxcontrib-bibtex
    - sphinxcontrib-spelling
    - sphinx_markdown_tables
    - recommonmark
    - sphinxcontrib-spelling
