find_package(JsonCpp 1.6.2 REQUIRED)

if (JSONCPP_FOUND)
    mark_as_advanced(CLEAR JSONCPP_INCLUDE_DIR)
    mark_as_advanced(CLEAR JSONCPP_LIBRARY)
    include_directories(${JSONCPP_INCLUDE_DIR})
    set(ENTWINE_JSONCPP_LIB_NAME ${JSONCPP_LIBRARY})
    set(ENTWINE_JSONCPP_INCLUDE_DIR ${JSONCPP_INCLUDE_DIR})
    set(JSON_CPP_LINK_TYPE PUBLIC)
    set(ENTWINE_HAVE_JSONCPP 1)
endif()

