if (WIN32)
    include (${CMAKE_CURRENT_LIST_DIR}/windows_compiler_options.cmake)
else()
    include (${CMAKE_CURRENT_LIST_DIR}/unix_compiler_options.cmake)
endif()

function(compiler_options target)
    system_compiler_options(${target})
    set_property(TARGET ${target} PROPERTY CXX_STANDARD 11)
    set_property(TARGET ${target} PROPERTY CXX_STANDARD_REQUIRED TRUE)
    set_property(TARGET ${target} PROPERTY POSITION_INDEPENDENT_CODE TRUE)
endfunction()
