# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  container:
      image: connormanning/entwine
      options: --privileged
      endpoint:  /bin/sh
  timeoutInMinutes: 360
  steps:
  - script: |
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX=/usr \
        ..
    displayName: 'CMake'

  - script: |
      cd build
      make
    displayName: 'Make'
  - script: |
      cd build
      make test
    displayName: 'Test'
