# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  container:
      image: pdal/pdal
      options: --privileged
  timeoutInMinutes: 360
  steps:
  - script: |
      sudo apt-get update -y;
      sudo apt-get install -y \
        autoconf \
        build-essential \
        cmake \
        git \
        liblzma-dev \
        libjsoncpp-dev \
        libssl-dev \
        libcurl4-openssl-dev \
        ninja-build \
        python-numpy \
        ninja-build \
        python-pip
      mkdir -p build
      cd build
      cmake -G "Ninja" \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX=/usr \
        ..

    displayName: 'CMake'

  - script: |
      cd build
      ninja
    displayName: 'Make'
  - script: |
      cd build
      ninja test
    displayName: 'Test'
