# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.13
  timeoutInMinutes: 360
  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      echo "Fast Finish"


  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      source activate base
      conda install -n base -c conda-forge --quiet --yes entwine --only-deps
    displayName: 'Add Entwine conda package dependencies'

  - script: |
      source activate base
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_INSTALL_PREFIX=/usr \
        ..
  - script: |
      source activate base
      cd build
      make
    displayName: 'Make'
  - script: |
      source activate base
      cd build
      make test
    displayName: 'Test'
