name: Build

on:
  push:
      paths-ignore:
          - 'doc/**'
  pull_request:
      paths-ignore:
          - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    env:
      CACHE_NUMBER: 0

    steps:
    - uses: actions/checkout@v4
    - name: Support longpaths
      run: git config --system core.longpaths true
      if: matrix.platform == 'windows-latest'
    - name: Cache Conda Environment
      uses: actions/cache@v4
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-${{ steps.get-date.outputs.today }}-conda-${{ env.CACHE_NUMBER }}
    - uses: mamba-org/setup-micromamba@v2
      with:
        init-shell: bash
        environment-file: "scripts/ci/environment.yml"
        environment-name: "entwine-build"
        cache-environment: true
        cache-downloads: true

    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'

    - name: CMake
      shell: bash -l {0}
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          export CC=cl.exe
          export CXX=cl.exe
        fi
        mkdir build
        cd build
        cmake .. \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DBUILD_SHARED_LIBS=ON \
          -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING=1 \
          -Dgtest_force_shared_crt=ON \
          ..

    - name: Compile
      shell: bash -l {0}
      run: |
        ninja install
      working-directory: ./build

    - name: Test
      shell: bash -l {0}
      run: |
        ctest -VV --output-on-failure
      working-directory: ./build

