name: OSX

on:
  push:
      paths-ignore:
          - 'doc/**'
  pull_request:
      paths-ignore:
          - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: OSX

    runs-on: 'macos-latest'
    strategy:
      fail-fast: true
      matrix:
        type: ['floating']
    env:
      BUILD_TYPE: ${{ matrix.type }}
      CACHE_NUMBER: 0

    steps:
    - uses: actions/checkout@v2
    - name: Support longpaths
      run: git config --system core.longpaths true
      if: matrix.platform == 'windows-latest'
    - name: Cache Conda Environment
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-${{ steps.get-date.outputs.today }}-conda-${{ env.CACHE_NUMBER }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        environment-file: scripts/ci/environment.yml
        python-version: "3.10"
        activate-environment: "entwine-build"
        use-mamba: true
        auto-update-conda: true

    - name: Setup
      shell: bash -l {0}
      run: |
          source ./scripts/ci/osx/setup.sh

    - name: CMake
      shell: bash -l {0}
      run: |
          source ../scripts/ci/osx/cmake.sh
      working-directory: ./build

    - name: Compile
      shell: bash -l {0}
      run: |
          source ../scripts/ci/osx/compile.sh
      working-directory: ./build

    - name: Test
      shell: bash -l {0}
      run: |
          source ../scripts/ci/osx/test.sh
      working-directory: ./build

