name: Test
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        shared: [ON, OFF]

    steps:
     - uses: actions/checkout@v4
     - uses: ilammy/msvc-dev-cmd@v1
       if: matrix.os == 'windows-latest'
     - name: Support longpaths
       run: git config --system core.longpaths true
       if: matrix.os == 'windows-latest'
     - uses: mamba-org/setup-micromamba@v1
       with:
           init-shell: bash
           environment-file: scripts/ci/environment.yml
           environment-name: "build"
           cache-environment: true
           cache-downloads: true

     - name: Setup
       shell: bash -l {0}
       run: |
           mkdir build

     - name: CMake
       shell: bash -l {0}

       run: |

        if [ "$RUNNER_OS" == "Windows" ]; then
        export CC=cl.exe
        export CXX=cl.exe
        export ENTWINE_LIBRARY_PATH=$CONDA_PREFIX/Library/lib
        export ENTWINE_INCLUDE_PATH=$CONDA_PREFIX/Library/include
        else
        export ENTWINE_LIBRARY_PATH=$CONDA_PREFIX/lib
        export ENTWINE_INCLUDE_PATH=$CONDA_PREFIX/include
        fi

        cmake   -G "Ninja"  \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
              -Dgtest_force_shared_crt=ON \
              -DBUILD_TESTING=ON \
              -DCMAKE_LIBRARY_PATH:FILEPATH=$ENTWINE_LIBRARY_PATH \
              -DCMAKE_INCLUDE_PATH:FILEPATH=$ENTWINE_INCLUDE_PATH \
              -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING=1 \
              -DBUILD_SHARED_LIBS=ON \
              ..


       working-directory: ./build

     - name: Compile
       shell: bash -l {0}
       run: |
          ninja
       working-directory: ./build

     - name: Test
       shell: bash -l {0}
       run: |
          ctest -VV --rerun-failed --output-on-failure
       working-directory: ./build

